spring.application.name=EstateSolution
# --- PostgreSQL Connection ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# --- JPA & Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# --- Server settings ---
server.port=${PORT:8082}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

google.cloud.project-id=${GOOGLE_CLOUD_PROJECT_ID:estatesol}
google.cloud.region=${GOOGLE_CLOUD_REGION:europe-west4}

logging.level.org.springframework.security=DEBUG
